### ISSUE TITLE
The UI icons disappeared.

### ISSUE THREAD

**Issue by Fallen-ice** [phaze-the-dumb/VRChat-Photo-Manager#1]
![1](https://github.com/phaze-the-dumb/VRChat-Photo-Manager-Rust/assets/96802720/3d3666ae-92a2-41b7-b34a-636a7b45bfee)
![2](https://github.com/phaze-the-dumb/VRChat-Photo-Manager-Rust/assets/96802720/6d9b2349-62d3-4704-9864-0dcd308e65f3)
I have installed it on both of my computers, but encountered the issue of UI icons disappearing on both.
By the way, I think I need the date jump functionality and a scroll bar.

**Comment by phaze-the-dumb** [comment]
Huh… looks like an issue with fontawesome, i’ll take a look when i got back home. I’ll move all the icons to be stored locally within the app.

**Comment by phaze-the-dumb** [comment]
Just wanna check before I push a release does this exe work? [https://cdn.phaz.uk/i/vrchat-photo-manager.exe](https://cdn.phaz.uk/i/vrchat-photo-manager.exe)

Make sure to close photo manager if you currently have it running as it won't start multiple instance of itself.

**Comment by phaze-the-dumb** [comment]
Okay, released a fix, if you fully restart your app (go into the tray, right click, close, then re-open it) it should automatically update.

Lemme know if that fixes it

**Comment by Fallen-ice** [comment]
Alright, it has been fixed. Thank you!
